### ISSUE TITLE
passwall功能栏平铺

### ISSUE THREAD

**Issue by WenWuuu** [gngpp/luci-theme-design#101]
Passwall上方的的功能列表是否能够更改为平铺展示，一行三个正好四行，如下图：
![image](https://user-images.githubusercontent.com/105963539/235481853-f7e4e0ff-2964-4284-9517-56ec031290b2.png)

**Comment by WenWuuu** [comment]
使用了一天体验非常好，会持续关注

**Comment by gngpp** [comment]
这样进度条就没必要存在了
