### ISSUE TITLE
交换机页面在1080P或者更大分辨率以上有布局问题

### ISSUE THREAD

**Issue by ssm1588** [gngpp/luci-theme-design#103]
具体表现为端口分布距离不一样，有的远有的近，看起来不协调，请大佬修复一下

**Comment by ssm1588** [comment]
![Uploading QQ拼音截图20230822103700.png…]()

**Comment by ssm1588** [comment]
![QQ拼音截图20230822103700](https://github.com/gngpp/luci-theme-design/assets/142860496/dfcf233c-cde1-4e3c-8111-9a62ca5e85a7)

**Comment by gngpp** [comment]
我没有机器，所以无法测试
