### ISSUE TITLE
iphone上菜单按钮位置错误

### ISSUE THREAD

**Issue by DoveKi** [gngpp/luci-theme-design#108]
截图是iphone12 菜单栏按钮在右边，测试iphone12和iphone14都一样在右边位置
拍照的8p和其他安卓机都是正常在左边
浏览器测试过chrome和safari都是一样的
怀疑iphone分辨率不是整数的原因，希望修复一下，用着很别扭
![8A409D2BA864D908FC6530043CFB06F8](https://github.com/gngpp/luci-theme-design/assets/8667391/52058a1c-b3d9-493e-a007-f188a618d004)
![2791CB23D42B76A5D39DEB958C49D00D](https://github.com/gngpp/luci-theme-design/assets/8667391/7812fa10-a226-49e2-897f-d1daca50c2e1)

**Comment by DoveKi** [comment]
@gngpp

**Comment by gngpp** [comment]
我都没有iPhone12怎么修，你苹果浏览器连Mac自己调试一下就知道了

**Comment by DoveKi** [comment]
> 我都没有iPhone12怎么修，你苹果浏览器连Mac自己调试一下就知道了

不知道怎么调 应该是分辨率问题吧

**Comment by gngpp** [comment]
#109

**Comment by DoveKi** [comment]
已经更新重新编译，和原来一样并没有修复
@gngpp 
![IMG_3443](https://github.com/gngpp/luci-theme-design/assets/8667391/e7743f91-8c93-4e69-82fc-f4a7c43e7acc)
![IMG_7952](https://github.com/gngpp/luci-theme-design/assets/8667391/a79e7bb3-f1b8-4f49-a215-fc86dd9bec23)

**Comment by gngpp** [comment]
哪没救了，只能等我有钱买iPhone14了
