### ISSUE TITLE
IOS17以后菜单按钮位置错位

### ISSUE THREAD

**Issue by DoveKi** [gngpp/luci-theme-design#111]
已经更新重新编译，和原来一样并没有修复
@gngpp 
![IMG_3443](https://github.com/gngpp/luci-theme-design/assets/8667391/e7743f91-8c93-4e69-82fc-f4a7c43e7acc)
![IMG_7952](https://github.com/gngpp/luci-theme-design/assets/8667391/a79e7bb3-f1b8-4f49-a215-fc86dd9bec23)

_Originally posted by @DoveKi in https://github.com/gngpp/luci-theme-design/issues/108#issuecomment-1790025785_

**Comment by gngpp** [comment]
有条件可以自己学学如何调试：https://cloud.tencent.com/developer/article/1680133

**Comment by DoveKi** [comment]
> 有条件可以自己学学如何调试：https://cloud.tencent.com/developer/article/1680133

搞好了不懂web调试啊 你看什么时候有空方便远程调一下
<img width="1634" alt="QQ20231102-230254@2x" src="https://github.com/gngpp/luci-theme-design/assets/8667391/aaaabe68-ca53-4c51-92ff-37c737fe28f3">

**Comment by DoveKi** [comment]
@gngpp 我擦 发现这个错位不是iphone型号的原因 是ios17的原因 
可能ios17 webkit api改了什么

**Comment by gngpp** [comment]
> @gngpp 我擦 发现这个错位不是iphone型号的原因 是ios17的原因 
> 可能IOS17 webkit改了
> 我模拟器试了ios15 ios16都是正常的。。。

模拟器没用，你得上真机调试，连上电脑safari就可以调试了，联系方式发我邮箱

**Comment by DoveKi** [comment]
> > @gngpp 我擦 发现这个错位不是iphone型号的原因 是ios17的原因
> > 可能IOS17 webkit改了
> > 我模拟器试了ios15 ios16都是正常的。。。
> 
> 模拟器没用，你得上真机调试，连上电脑safari就可以调试了，联系方式发我邮箱

我试了一下 模拟器和真机对应的
ios16模拟器正常 ios17模拟器就错位
联系方式发你邮箱

**Comment by gngpp** [comment]
gngppz@gmail.com

**Comment by DoveKi** [comment]
已发





------------------ 原始邮件 ------------------
发件人: gngpp ***@***.***&gt;
发送时间: 2023年11月3日 20:43
收件人: gngpp/luci-theme-design ***@***.***&gt;
抄送: DoveKi ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [gngpp/luci-theme-design] IOS17以后菜单按钮位置错位 (Issue #111)





 
***@***.***

**Comment by DoveKi** [comment]
> [gngppz@gmail.com](mailto:gngppz@gmail.com)

能收到么 不会被屏蔽了吧

**Comment by gngpp** [comment]
> > [gngppz@gmail.com](mailto:gngppz@gmail.com)
> 
> 能收到么 不会被屏蔽了吧

你这账号都屏蔽所有人了

**Comment by DoveKi** [comment]
> > > [gngppz@gmail.com](mailto:gngppz@gmail.com)
> > 
> > 
> > 能收到么 不会被屏蔽了吧
> 
> 你这账号都屏蔽所有人了

没有啊 是v
不然你发来我加你

**Comment by gngpp** [comment]
> > > > [gngppz@gmail.com](mailto:gngppz@gmail.com)
> > > 
> > > 
> > > 能收到么 不会被屏蔽了吧
> > 
> > 
> > 你这账号都屏蔽所有人了
> 
> 没有啊 是v 不然你发来我加你

qq942203377
