### ISSUE TITLE
在没有安装openclash插件的情况下，左下角导航栏多出openclash选项，点击后会跳转错误页面

### ISSUE THREAD

**Issue by colinwjd** [gngpp/luci-theme-design#113]
![image](https://github.com/gngpp/luci-theme-design/assets/7942918/b5d031ab-cd4d-43fd-826b-cba708a1b54e)
![image](https://github.com/gngpp/luci-theme-design/assets/7942918/c61c4276-62d3-4e05-9b18-c99923ac46d7)

**Comment by gngpp** [comment]
你可以装主题插件，然后把把链接换成ssrp

**Comment by colinwjd** [comment]
> 你可以装主题插件，然后把链接换成ssrp
如果不安装主题配置插件的话，能否通过手动配置关闭这个导航条呢？

**Comment by colinwjd** [comment]
> 你可以装主题插件，然后把链接换成ssrp

如果不安装主题配置插件的话，能否通过手动配置关闭这个导航条呢？

**Comment by colinwjd** [comment]
手动添加配置文件`/etc/config/design`后解决了，哈哈，感谢作者
```
config global
	option mode 'dark'
	option navbar 'display'
	option navbar_proxy 'openclash'
```

**Comment by clsddy** [comment]
> 手动添加配置文件`/etc/config/design`后解决了，哈哈，感谢作者
> 
> ```
> config global
> 	option mode 'dark'
> 	option navbar 'display'
> 	option navbar_proxy 'shadowsocksr'
> ```

这是关闭,还是替换掉了

**Comment by clsddy** [comment]
> > > 手动添加配置文件`/etc/config/design`后解决了，哈哈，感谢作者
> > > ```
> > > config global
> > > 	option mode 'dark'
> > > 	option navbar 'display'
> > > 	option navbar_proxy 'shadowsocksr'
> > > ```
> > 
> > 
> > 这是关闭,还是替换掉了
> 
> 替换成了ssr，另外如果是自己编译固件的话，也可以直接修改代码替换成ssr，这样就不用添加配置了
> 
> ```
> sed -i "s/local navbar_proxy = 'openclash'/local navbar_proxy = 'shadowsocksr'/g" feeds/luci/themes/luci-theme-design/luasrc/view/themes/design/header.htm
> ```

用的人家闭源固件,自己编译不成https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=8286839

**Comment by clsddy** [comment]
sed -i "s/local navbar_proxy = 'openclash'/local navbar_proxy = 'shadowsocksr'/g" feeds/luci/themes/luci-theme-design/luasrc/view/themes/design/header.htm

是仅仅需要这一条代码,对相应配置文件里的内容替换就行了吗

**Comment by clsddy** [comment]
> > sed -i "s/local navbar_proxy = 'openclash'/local navbar_proxy = 'shadowsocksr'/g" feeds/luci/themes/luci-theme-design/luasrc/view/themes/design/header.htm
> > 是仅仅需要这一条代码,对相应配置文件里的内容替换就行了吗
> 
> 不自己编译的话，只需要添加配置文件`/etc/config/design`就可以了，内容就是上面回复的那些

如果我想更改第二第三个图标的链接怎么替换呢

**Comment by gngpp** [comment]
我把clash删掉吧，切回默认ssrp，clash的时代已经过去了

**Comment by clsddy** [comment]
> 我把clash删掉吧，切回默认ssrp，clash的时代已经过去了

已经卸载了,不好用,在用passwall,
ssrp和passwall是基本上一样的吧

**Comment by gngpp** [comment]
https://github.com/gngpp/luci-theme-design/releases/tag/v5.7.9-20231122

**Comment by clsddy** [comment]
> https://github.com/gngpp/luci-theme-design/releases/tag/v5.7.9-20231122

大佬请问一下,开了SSR plus+,不正常分配IP是怎么回事,静态手动才能链接上

**Comment by clsddy** [comment]
请问一下,开了SSR plus+,不正常分配IP是怎么回事,静态手动才能链接上
