### ISSUE TITLE
immortalwrt是否可用

### ISSUE THREAD

**Issue by h0we** [gngpp/luci-theme-design#118]
原版neobird在immortalwrt-21.02中不工作，此版本不知是否兼容immortalwrt-21.02。

**Comment by gngpp** [comment]
21.02 需要用js分支，由@papagaye744维护

**Comment by papagaye744** [comment]
用js的分支兼容的，没有预编译的包，你需要用sdk或者op源码拉代码后编译成ipk或者集成到固件
