### ISSUE TITLE
请问第四个状态的按钮功能可否更改?

### ISSUE THREAD

**Issue by wxchil** [gngpp/luci-theme-design#124]
就是下面这个负载的图标,因为我另行安装了netdata,而且也很习惯使用
请问如何可以更改下呢?
![image](https://github.com/gngpp/luci-theme-design/assets/44988562/6357755c-a1ae-428c-8668-5e93798d963a)

**Comment by combat60** [comment]
可以自己到/usr/lib/lua/luci/view/themes/design/header.htm 里面改哦 第四个图标是realtime 搜一下就找到了

**Comment by wxchil** [comment]
好的，谢谢
