### ISSUE TITLE
[js]显示异常

### ISSUE THREAD

**Issue by ObcbO** [gngpp/luci-theme-design#21]
| 登录 | 侧边栏 |
| --- | --- |
| ![Screenshot_2023-02-23-21-55-24-455_mark via](https://user-images.githubusercontent.com/49872497/220928546-97b1f717-bef7-406f-bd9b-597be50b3417.jpg) | ![Screenshot_2023-02-23-21-55-07-920_mark via](https://user-images.githubusercontent.com/49872497/220928556-2b19e3a5-de73-433f-8f4c-c1e328708734.jpg) |

固件版本 OpenWrt 21.02-SNAPSHOT r16399+142-c67509efd7 / LuCI openwrt-22.03 branch git-21.284.67084-e4d24f0

**Comment by gngpp** [comment]
你这是新编译的吗，还是下载release发布的，release发布的是过时的。

**Comment by ObcbO** [comment]
> 你这是新编译的吗，还是下载release发布的，release发布的是过时的。

新编译的

**Comment by gngpp** [comment]
> > 你这是新编译的吗，还是下载release发布的，release发布的是过时的。
> 
> 新编译的

<img width="1475" alt="image" src="https://user-images.githubusercontent.com/51810656/221089434-a833c445-6ed3-4d10-9d00-774189833028.png">
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/51810656/221089457-2559159e-8c26-4db9-9d01-ea803446b1b3.png">
我等会看看吧，我这边正常

**Comment by ObcbO** [comment]
> > > 你这是新编译的吗，还是下载release发布的，release发布的是过时的。
> > 
> > 
> > 新编译的
> 
> <img alt="image" width="1475" src="https://user-images.githubusercontent.com/51810656/221089434-a833c445-6ed3-4d10-9d00-774189833028.png">
> 
> <img alt="image" width="1475" src="https://user-images.githubusercontent.com/51810656/221089457-2559159e-8c26-4db9-9d01-ea803446b1b3.png">
> 
> 我等会看看吧，我这边正常

而且横屏的布局还是竖的样子

**Comment by gngpp** [comment]
> ![Screenshot_2023-02-23-21-55-24-455_mark via](https://user-images.githubusercontent.com/49872497/220928546-97b1f717-bef7-406f-bd9b-597be50b3417.jpg) ![Screenshot_2023-02-23-21-55-07-920_mark via](https://user-images.githubusercontent.com/49872497/220928556-2b19e3a5-de73-433f-8f4c-c1e328708734.jpg)
> 
> 固件版本 OpenWrt 21.02-SNAPSHOT r16399+142-c67509efd7 / LuCI openwrt-22.03 branch git-21.284.67084-e4d24f0

<img width="1475" alt="image" src="https://user-images.githubusercontent.com/51810656/221101008-74874bf8-7d22-4338-9201-f7ce426567d0.png">
没有问题，你下载最新看看

**Comment by castillofrancodamian** [comment]
It looks like this to me, without that font.

![Screenshot_20230224_211454](https://user-images.githubusercontent.com/47670442/221324187-2e635a6d-2de1-47d5-bcc9-12429c53d17f.png)

**Comment by ObcbO** [comment]
> [gngpp](https://github.com/gngpp) It looks like this to me, without that font.
> 
> ![Screenshot_20230224_211454](https://user-images.githubusercontent.com/47670442/221324187-2e635a6d-2de1-47d5-bcc9-12429c53d17f.png)

Are you also using the "js" branch? Maybe I'm configuring it wrong

**Comment by ObcbO** [comment]
> > ![Screenshot_2023-02-23-21-55-24-455_mark via](https://user-images.githubusercontent.com/49872497/220928546-97b1f717-bef7-406f-bd9b-597be50b3417.jpg) ![Screenshot_2023-02-23-21-55-07-920_mark via](https://user-images.githubusercontent.com/49872497/220928556-2b19e3a5-de73-433f-8f4c-c1e328708734.jpg)
> > 固件版本 OpenWrt 21.02-SNAPSHOT r16399+142-c67509efd7 / LuCI openwrt-22.03 branch git-21.284.67084-e4d24f0
> 
> <img alt="image" width="1475" src="https://user-images.githubusercontent.com/51810656/221101008-74874bf8-7d22-4338-9201-f7ce426567d0.png">
> 
> 没有问题，你下载最新看看

问题依旧，可能是我的问题

https://github.com/ObcbO/OpenWrt-GL.iNet-AXT1800
https://github.com/ObcbO/Theme_Packages

但我找不出来（）

**Comment by gngpp** [comment]
> > > ![Screenshot_2023-02-23-21-55-24-455_mark via](https://user-images.githubusercontent.com/49872497/220928546-97b1f717-bef7-406f-bd9b-597be50b3417.jpg) ![Screenshot_2023-02-23-21-55-07-920_mark via](https://user-images.githubusercontent.com/49872497/220928556-2b19e3a5-de73-433f-8f4c-c1e328708734.jpg)
> > > 固件版本 OpenWrt 21.02-SNAPSHOT r16399+142-c67509efd7 / LuCI openwrt-22.03 branch git-21.284.67084-e4d24f0
> > 
> > 
> > <img alt="image" width="1475" src="https://user-images.githubusercontent.com/51810656/221101008-74874bf8-7d22-4338-9201-f7ce426567d0.png">
> > 没有问题，你下载最新看看
> 
> 问题依旧，可能是我的问题
> 
> https://github.com/ObcbO/OpenWrt-GL.iNet-AXT1800 https://github.com/ObcbO/Theme_Packages
> 
> 但我找不出来（）

下载发布的https://github.com/gngpp/luci-theme-design/releases/download/v6.0-20230224-dev/luci-theme-design_6.0-20230224_all.ipk，你需要换谷歌浏览器来看看有没有问题，我测了安卓/ios都没有问题

**Comment by ObcbO** [comment]
> > > > ![Screenshot_2023-02-23-21-55-24-455_mark via](https://user-images.githubusercontent.com/49872497/220928546-97b1f717-bef7-406f-bd9b-597be50b3417.jpg) ![Screenshot_2023-02-23-21-55-07-920_mark via](https://user-images.githubusercontent.com/49872497/220928556-2b19e3a5-de73-433f-8f4c-c1e328708734.jpg)
> > > > 固件版本 OpenWrt 21.02-SNAPSHOT r16399+142-c67509efd7 / LuCI openwrt-22.03 branch git-21.284.67084-e4d24f0
> > > 
> > > 
> > > <img alt="image" width="1475" src="https://user-images.githubusercontent.com/51810656/221101008-74874bf8-7d22-4338-9201-f7ce426567d0.png">
> > > 没有问题，你下载最新看看
> > 
> > 
> > 问题依旧，可能是我的问题
> > https://github.com/ObcbO/OpenWrt-GL.iNet-AXT1800 https://github.com/ObcbO/Theme_Packages
> > 但我找不出来（）
> 
> * 下载发布的https://github.com/gngpp/luci-theme-design/releases/download/v6.0-20230224-dev/luci-theme-design_6.0-20230224_all.ipk
> * 你需要换谷歌浏览器来看看有没有问题，我测了安卓/ios都没有问题

问题照旧

**Comment by castillofrancodamian** [comment]
> > [gngpp](https://github.com/gngpp) It looks like this to me, without that font.
> > ![Screenshot_20230224_211454](https://user-images.githubusercontent.com/47670442/221324187-2e635a6d-2de1-47d5-bcc9-12429c53d17f.png)
> 
> Are you also using the "js" branch? Maybe I'm configuring it wrong

Yes, I use the "js" branch.
```
[franco@pc luci-theme-design]$ pwd
/run/media/franco/hdd2tb/openwrt/package/luci-theme-design
[franco@pc luci-theme-design]$ git branch
* js
  main
[franco@pc luci-theme-design]$ 

```

**Comment by gngpp** [comment]
> * 你需要换谷歌浏览器来看看有

使用什么浏览器？改天看看是什么毛病，有些浏览器可能会有奇奇怪怪问题

**Comment by ObcbO** [comment]
> > * 你需要换谷歌浏览器来看看有
> 
> 使用什么浏览器？改天看看是什么毛病，有些浏览器可能会有奇奇怪怪问题

via浏览器
https://viayoo.com/

UA
```
Mozilla/5.0 (Linux; Android 13; M2102K1AC Build/TKQ1.220829.002) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.97 Mobile Safari/537.36
```

**Comment by ObcbO** [comment]
> > > [gngpp](https://github.com/gngpp) It looks like this to me, without that font.
> > > ![Screenshot_20230224_211454](https://user-images.githubusercontent.com/47670442/221324187-2e635a6d-2de1-47d5-bcc9-12429c53d17f.png)
> > 
> > 
> > Are you also using the "js" branch? Maybe I'm configuring it wrong
> 
> Yes, I use the "js" branch.
> 
> ```
> [franco@pc luci-theme-design]$ pwd
> /run/media/franco/hdd2tb/openwrt/package/luci-theme-design
> [franco@pc luci-theme-design]$ git branch
> * js
>   main
> [franco@pc luci-theme-design]$ 
> ```

The problem occurs on via browser I use, thank you for your help

**Comment by castillofrancodamian** [comment]
@ObcbO But my "problem" keeps happening. I don't know if another package needs to be installed or what to have the most "beautiful" type of font.

**Comment by ObcbO** [comment]
> @ObcbO But my "problem" keeps happening. I don't know if another package needs to be installed or what to do to have the most "beautiful" type of font.

Here
https://github.com/gngpp/luci-theme-design/tree/main/htdocs/luci-static/design/fonts

**Comment by castillofrancodamian** [comment]
@ObcbO The "js" branch is not updated like the "main" branch.

**Comment by ObcbO** [comment]
> @ObcbO The "js" branch is not updated like the "main" branch.

js branch
https://github.com/gngpp/luci-theme-design/tree/js/htdocs/luci-static/design/fonts

**Comment by castillofrancodamian** [comment]
@ObcbO And what do I do with it? I understand that by selecting the "js" branch, everything should work and be seen correctly.

**Comment by ObcbO** [comment]
> @ObcbO And what do I do with it? I understand that by selecting the "js" branch, everything should work and be seen correctly.

fork and replace the original file

**Comment by castillofrancodamian** [comment]
@ObcbO What do you mean by "fork"?

**Comment by castillofrancodamian** [comment]
file:///home/franco/Escritorio/Screenshot_20230225_175023.png

**Comment by gngpp** [comment]
The JS version is still in the development stage. If you have suggestions or can fix bugs, you are welcome to submit a pr, because I may not have much time to maintain the js branch, but I will spare time to improve the theme

**Comment by gngpp** [comment]
> @ObcbO But my "problem" keeps happening. I don't know if another package needs to be installed or what to do to have the most "beautiful" type of font.

In fact, the font files of the two branches are the same, because the css style is not adjusted properly

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/51810656/221385706-ccaca5cd-db14-4b9e-b8f5-e5d5a7deb86a.png">

The font may be related to your operating system font

**Comment by castillofrancodamian** [comment]
@gngpp I tried on an Android device and it shows the correct font, but there are still other errors like [this](https://github.com/gngpp/luci-theme-design/issues/23).

**Comment by ningnao** [comment]
我遇到了相同的问题，js分支使用最新的源码编译的
![image](https://user-images.githubusercontent.com/118373565/224408796-6fe8b69f-f0d9-4538-94d7-88d73e88eaf6.png)

**Comment by castillofrancodamian** [comment]
> 我遇到了相同的问题，js分支使用最新的源码编译的 ![image](https://user-images.githubusercontent.com/118373565/224408796-6fe8b69f-f0d9-4538-94d7-88d73e88eaf6.png)

What problem have you detected?

**Comment by gngpp** [comment]
> 我遇到了相同的问题，js分支使用最新的源码编译的 ![image](https://user-images.githubusercontent.com/118373565/224408796-6fe8b69f-f0d9-4538-94d7-88d73e88eaf6.png)

看起来是资源加载有问题（有些浏览器特性不支持，或许换谷歌浏览器就解决了），但我目前现有设备上编译没有这个问题，加上暂时没有精力去测试，也没有人参与维护

**Comment by castillofrancodamian** [comment]
@gngpp Not everyone knows how to program. If they knew they would already be collaborating.

**Comment by gngpp** [comment]
> @gngpp Not everyone knows how to program. If they knew they would already be collaborating.

I'm done with the basic response framework, and all I need to do is tweak the css styles. This takes a lot of time to adjust the display style

**Comment by ningnao** [comment]
> > 我遇到了相同的问题，js分支使用最新的源码编译的![图像](https://user-images.githubusercontent.com/118373565/224408796-6fe8b69f-f0d9-4538-94d7-88d73e88eaf6.png)
> 
> 看起来是资源加载有问题（有些浏览器特性不支持，或许换谷歌浏览器就解决了），但我目前现有设备上编译没有这个问题，加上暂时没有精力去测试，也没有人参与维护

我这就是在chrome上的显示效果.. 另外手机上chrome也是同样的问题

**Comment by 281677160** [comment]
> > > 我遇到了相同的问题，js分支使用最新的源码编译的![图像](https://user-images.githubusercontent.com/118373565/224408796-6fe8b69f-f0d9-4538-94d7-88d73e88eaf6.png)
> > 
> > 
> > 看起来是资源加载有问题（有些浏览器特性不支持，或许换谷歌浏览器就解决了），但我目前现有设备上编译没有这个问题，加上暂时没有精力去测试，也没有人参与维护
> 
> 我这就是在chrome上的显示效果.. 另外手机上chrome也是同样的问题

同样问题，在官方OPENWRT还是其他人的都一样问题，好像就天灵的21.02没问题，也是使用chrome浏览器

**Comment by Curious-r** [comment]
我也遇到同样的问题，随固件编译的js分支。
无论是22.03还是master，都是这样。
浏览器是 edge，手机和电脑都是

**Comment by gngpp** [comment]
#105 #104
