### ISSUE TITLE
能否为 “图标2” 添加多个选项设置以便选择其它插件

### ISSUE THREAD

**Issue by mitsukileung** [gngpp/luci-theme-design#22]
能否为 “图标2” 添加多个选项设置以便选择其它插件
如SSRP OPENCLASH PASSWALL VSSR 等等

**Comment by gngpp** [comment]
> 

可以的，你有什么想法，目前是可以根据一些优先级去实现不同图标或者链接。但是没有一个折中办法，最好就是硬编码多个分支来区分让用户选择版本编译，或许弄个菜单选项。

**Comment by mitsukileung** [comment]
只是提个见意而已。如大佬你所说加个菜单选项可能会比较方便，或者像 luci-theme-argon 哪样加个 luci-app-argon-config。
因为现在编译固件都带有不止一个“富强”插件，这样便于随时设换不如的插件

**Comment by gngpp** [comment]
> 只是提个见意而已。如大佬你所说加个菜单选项可能会比较方便，或者像 luci-theme-argon 哪样加个 luci-app-argon-config。 因为现在编译固件都带有不止一个“富强”插件，这样便于随时设换不如的插件

可以

**Comment by mitsukileung** [comment]
期待大佬的更新！

**Comment by sxml** [comment]
图标二只能小猫？图标5 多余吧？有谁没事就改密码

**Comment by sxml** [comment]
额 我安装 
luci-theme-design v5.3.7-20230305 
luci-app-design-config v1.2-20230302 
Design 主题设置 只能改变 导航栏代理  主题模式 无效？

**Comment by gngpp** [comment]
> 

![Screenshot_2023-03-06-00-17-17-271_com android chrome](https://user-images.githubusercontent.com/51810656/222972512-dc61455e-5241-41e9-bfa2-c07d5608fd10.jpg)
![Screenshot_2023-03-06-00-16-52-511_com android chrome](https://user-images.githubusercontent.com/51810656/222972529-c7b929e6-f21a-4bd5-a1b3-1ba4786814db.jpg)
![Screenshot_2023-03-06-00-17-20-587_com android chrome](https://user-images.githubusercontent.com/51810656/222972548-a47a6130-1ac3-4ebb-884a-2a5d04b31933.jpg)
没有问题，记得清浏览器缓存

**Comment by sxml** [comment]
> > 
> 
> ![Screenshot_2023-03-06-00-17-17-271_com android chrome](https://user-images.githubusercontent.com/51810656/222972512-dc61455e-5241-41e9-bfa2-c07d5608fd10.jpg) ![Screenshot_2023-03-06-00-16-52-511_com android chrome](https://user-images.githubusercontent.com/51810656/222972529-c7b929e6-f21a-4bd5-a1b3-1ba4786814db.jpg) ![Screenshot_2023-03-06-00-17-20-587_com android chrome](https://user-images.githubusercontent.com/51810656/222972548-a47a6130-1ac3-4ebb-884a-2a5d04b31933.jpg) 没有问题，记得清浏览器存档

谢谢！缓存问题 换个浏览器可以了
