### ISSUE TITLE
界面卡住了

### ISSUE THREAD

**Issue by mitsukileung** [gngpp/luci-theme-design#25]
界面卡住，输入密码可以登入。但是登入后左边菜单栏失效，只有左下角哪几个图标还能用。main 分支

![无标题](https://user-images.githubusercontent.com/38887306/222953895-8850c5ee-eef5-490a-bb15-2ad8b8a7ef7e.png)

**Comment by gngpp** [comment]
> 界面卡住，输入密码可以登入。但是登入后左边菜单栏失效，只有左下角哪几个图标还能用。main 分支
> 
> ![无标题](https://user-images.githubusercontent.com/38887306/222953895-8850c5ee-eef5-490a-bb15-2ad8b8a7ef7e.png)

是不是下5.3.6老版本了，我弄完压缩有点问题，等几分钟，出5.3.7

**Comment by gngpp** [comment]
> 界面卡住，输入密码可以登入。但是登入后左边菜单栏失效，只有左下角哪几个图标还能用。main 分支
> 
> ![无标题](https://user-images.githubusercontent.com/38887306/222953895-8850c5ee-eef5-490a-bb15-2ad8b8a7ef7e.png)

https://github.com/gngpp/luci-theme-design/releases/tag/v5.3.7-20230305

**Comment by gngpp** [comment]
> 界面卡住，输入密码可以登入。但是登入后左边菜单栏失效，只有左下角哪几个图标还能用。main 分支
> 
> ![无标题](https://user-images.githubusercontent.com/38887306/222953895-8850c5ee-eef5-490a-bb15-2ad8b8a7ef7e.png)

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/51810656/222954701-e449627a-f454-4bb7-9bc7-46e7863d4fb3.png">
新版测试没问题
