### ISSUE TITLE
建议把navbar隐藏

### ISSUE THREAD

**Issue by cjlhll** [gngpp/luci-theme-design#26]
感觉没什么用。又不会天天上这操作。多点两下也不累。这个还遮挡屏幕内容。

**Comment by gngpp** [comment]
> 感觉没什么用。又不会天天上这操作。多点两下也不累。这个还遮挡屏幕内容。

彻底隐藏是不可能的，大众口味不同。
你可以使用插件进行设置隐藏
plugins：https://github.com/gngpp/luci-app-design-config/releases/tag/v1.3
release：https://github.com/gngpp/luci-theme-design/releases/tag/v5.3.9-20230306
![image](https://user-images.githubusercontent.com/51810656/223126964-47855bec-7cfa-4042-b375-ff488420ab4b.png)
