### ISSUE TITLE
Design-config 配置了没生效

### ISSUE THREAD

**Issue by asiaon123** [gngpp/luci-theme-design#27]

**Comment by gngpp** [comment]
> 

下载最新版本，并且安装后重启，清浏览器缓存

**Comment by asiaon123** [comment]
还是没用 修改配置重启后无痕模式打开的

**Comment by gngpp** [comment]
> 还是没用 修改配置重启后无痕模式打开的

你什么浏览器，我咋用好好

**Comment by gngpp** [comment]
> 还是没用 修改配置重启后无痕模式打开的

![Screenshot_2023-03-09-10-44-26-880_com.android.chrome.jpg](https://user-images.githubusercontent.com/51810656/223902691-bfbefbd9-59b2-4f1c-a40b-91e2ddc726b8.jpg)

![Screenshot_2023-03-09-10-44-38-148_com.android.chrome.jpg](https://user-images.githubusercontent.com/51810656/223902703-a967d5df-4352-4148-9979-2424c05dbc33.jpg)

**Comment by gngpp** [comment]
> 还是没用 修改配置重启后无痕模式打开的

![Screenshot_2023-03-09-10-45-30-247_com.android.chrome.jpg](https://user-images.githubusercontent.com/51810656/223902819-6c4529f5-ac02-4a3b-ae72-c22d6f779685.jpg)

**Comment by asiaon123** [comment]
好的 我这边 luci-theme-design 版本不够 我看上游还没有更新 我更新下试试 谢谢

**Comment by 281677160** [comment]
作者大佬，用你的IPK安装就可以，但是用源码编译的话，怎么拉最新源码，编译出来都不是5.4.2版本的，是5.3.1的
Design-config 配置将会没效

**Comment by gngpp** [comment]
> 作者大佬，用你的IPK安装就可以，但是用源码编译的话，怎么拉最新源码，编译出来都不是5.4.2版本的，是5.3.1的 Design-config 配置将会没效
直接拉，就是最新的
git clone https://github.com/gngpp/luci-theme-design.git package/luci-theme-design
make menuconfig # choose LUCI->Theme->Luci-theme-design
make V=s

**Comment by 281677160** [comment]
> > 作者大佬，用你的IPK安装就可以，但是用源码编译的话，怎么拉最新源码，编译出来都不是5.4.2版本的，是5.3.1的 Design-config 配置将会没效
> > 直接拉，就是最新的
> > git clone https://github.com/gngpp/luci-theme-design.git package/luci-theme-design
> > make menuconfig # choose LUCI->Theme->Luci-theme-design
> > make V=s

没用，好神奇的操作，我本地测试了，云编译测试了，云编译的时候特意SSH连接检查代码，代码是最新的
luci-theme-design/Makefile文件也看了，也是最新的，编译出来的是5.3.1的

**Comment by asiaon123** [comment]
> > > 作者大佬，用你的IPK安装就可以，但是用源码编译的话，怎么拉最新源码，编译出来都不是5.4.2版本的，是5.3.1的 Design-config 配置将会没效
> > > 直接拉，就是最新的
> > > git clone https://github.com/gngpp/luci-theme-design.git package/luci-theme-design
> > > make menuconfig # choose LUCI->Theme->Luci-theme-design
> > > make V=s
> 
> 没用，好神奇的操作，我本地测试了，云编译测试了，云编译的时候特意SSH连接检查代码，代码是最新的 luci-theme-design/Makefile文件也看了，也是最新的，编译出来的是5.3.1的

你用的lede， lede 的代码不是最新的，要等他们更新

**Comment by 281677160** [comment]
> > > > 作者大佬，用你的IPK安装就可以，但是用源码编译的话，怎么拉最新源码，编译出来都不是5.4.2版本的，是5.3.1的 Design-config 配置将会没效
> > > > 直接拉，就是最新的
> > > > git clone https://github.com/gngpp/luci-theme-design.git package/luci-theme-design
> > > > make menuconfig # choose LUCI->Theme->Luci-theme-design
> > > > make V=s
> > 
> > 
> > 没用，好神奇的操作，我本地测试了，云编译测试了，云编译的时候特意SSH连接检查代码，代码是最新的 luci-theme-design/Makefile文件也看了，也是最新的，编译出
> 
> > > > 作者大佬，用你的IPK安装就可以，但是用源码编译的话，怎么拉最新源码，编译出来都不是5.4.2版本的，是5.3.1的 Design-config 配置将会没效
> > > > 直接拉，就是最新的
> > > > git clone https://github.com/gngpp/luci-theme-design.git package/luci-theme-design
> > > > make menuconfig # choose LUCI->Theme->Luci-theme-design
> > > > make V=s
> > 
> > 
> > 没用，好神奇的操作，我本地测试了，云编译测试了，云编译的时候特意SSH连接检查代码，代码是最新的 luci-theme-design/Makefile文件也看了，也是最新的，编译出来的是5.3.1的
> 
> 如果你拉最新的还是编译到旧的，就是缓存问题

楼主提醒了，就是LEDE源码自带此主题了，看了源码自带的就是5.3.1的搞我研究半天了，哈哈，我删除源码自带的再搞搞看

**Comment by 281677160** [comment]
大佬，提个个人认为的修改遇见哈，不过改不改也没所谓吧，就是感觉改了或者比较好

![QQ截图20230309155516](https://user-images.githubusercontent.com/66651997/223957657-bffc32e0-c847-4193-b39b-7cda9cbe08ee.png)

![QQ截图20230309155547](https://user-images.githubusercontent.com/66651997/223957687-e6313dba-0dff-4038-bf6d-ef85873a3124.png)
