### ISSUE TITLE
字体中 7 显示不出来

### ISSUE THREAD

**Issue by asiaon123** [gngpp/luci-theme-design#28]
如下图： 应该为B70，7丢失了

![image](https://user-images.githubusercontent.com/5396968/224063249-9c82d5e6-f9b8-482b-bbcb-467a71dacde7.png)

下载的字体里好像不完整 缺少了这个

![image](https://user-images.githubusercontent.com/5396968/224063686-39cb55d4-d919-411d-84fc-88e8710b29f1.png)

浏览器是chrome最新版，edge也试了，也没有7

**Comment by gngpp** [comment]
> 如下图： 应该为B70，7丢失了
> 
> ![image](https://user-images.githubusercontent.com/5396968/224063249-9c82d5e6-f9b8-482b-bbcb-467a71dacde7.png)
> 
> 下载的字体里好像不完整 缺少了这个
> 
> ![image](https://user-images.githubusercontent.com/5396968/224063686-39cb55d4-d919-411d-84fc-88e8710b29f1.png)
> 
> 浏览器是chrome最新版，edge也试了，也没有7

https://github.com/gngpp/luci-theme-design/releases/tag/v5.4.3-20230310
