### ISSUE TITLE
[main]菜单"防火墙"加载失败时，菜单栏无法展开

### ISSUE THREAD

**Issue by threerog** [gngpp/luci-theme-design#29]
点击左侧"服务"菜单栏里的第一个插件服务(passwall)后，整个左侧菜单栏会全部收缩，再次展开服务菜单栏时，第一个服务和第二个服务都处于选中状态。

**Comment by gngpp** [comment]
> 点击左侧"服务"菜单栏里的第一个插件服务(passwall)后，整个左侧菜单栏会全部收缩，再次展开服务菜单栏时，第一个服务和第二个服务都处于选中状态。

这个是插件问题，你用其他主题也是一样。我暂时没搞懂pw插件的逻辑

**Comment by threerog** [comment]
我现在使用的`luci-theme-argon v1.7.3`就没有这个问题
我是基于lede版编译

**Comment by threerog** [comment]
lean lede只能使用[luci-theme-argon v1.7.3](https://github.com/jerrykuku/luci-theme-argon/releases/tag/v1.7.3)

**Comment by threerog** [comment]
我全部测试一遍了，发现点击`状态>防火墙`也存在这个问题

**Comment by gngpp** [comment]
> 我现在使用的`luci-theme-argon v1.7.3`就没有这个问题 我是基于lede版编译

可能他们修复了

**Comment by gngpp** [comment]
> 我全部测试一遍了，发现design点击`状态>防火墙`也存在这个问题

我看了argon提交，是修复了

**Comment by threerog** [comment]
那design也可以修复吧

**Comment by gngpp** [comment]
> 点击左侧"服务"菜单栏里的第一个插件服务(passwall)后，整个左侧菜单栏会全部收缩，再次展开服务菜单栏时，第一个服务和第二个服务都处于选中状态。



> 点击左侧"服务"菜单栏里的第一个插件服务(passwall)后，整个左侧菜单栏会全部收缩，再次展开服务菜单栏时，第一个服务和第二个服务都处于选中状态。



> 点击左侧"服务"菜单栏里的第一个插件服务(passwall)后，整个左侧菜单栏会全部收缩，再次展开服务菜单栏时，第一个服务和第二个服务都处于选中状态。

https://github.com/gngpp/luci-theme-design/releases/tag/v5.4.9-20230316

**Comment by threerog** [comment]
测试了一下最新版 感觉体验不太好 非常不丝滑 
![D0FC656EBA47321B8F042558977FA674](https://user-images.githubusercontent.com/87128510/225755874-ba373aef-c1d2-42d3-bf0e-4900cb2fb594.png)

**Comment by gngpp** [comment]
> 测试了一下最新版 感觉体验不太好 非常不丝滑 ![D0FC656EBA47321B8F042558977FA674](https://user-images.githubusercontent.com/87128510/225755874-ba373aef-c1d2-42d3-bf0e-4900cb2fb594.png)

你录个视频看看是不是不丝滑
