### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by GuessMine** [gngpp/luci-theme-design#31]
相较于之前的版本，后面这几个版本侧边栏打开明细变慢，有拖拽感

**Comment by gngpp** [comment]
> 相较于之前的版本，后面这几个版本侧边栏打开明细变慢，有拖拽感

那个动画

**Comment by GuessMine** [comment]
左侧菜单栏打开与关闭

**Comment by GuessMine** [comment]
是在在手机上操作

**Comment by gngpp** [comment]
> 左侧菜单栏打开与关闭

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions

**Comment by GuessMine** [comment]
https://user-images.githubusercontent.com/18162475/225789457-81c0e7db-f56e-4334-bd9b-d52d456b57c8.MOV

**Comment by GuessMine** [comment]
https://user-images.githubusercontent.com/18162475/225789493-6f469814-102d-4807-8bcf-3a0b85a5c7ef.MOV

**Comment by GuessMine** [comment]
一个是4.5的版本，一个是最新的

**Comment by gngpp** [comment]
> 一个是4.5的版本，一个是最新的

就是动画啊，我调的时间长了一点，之前好像是0.1秒，现在是0.2

**Comment by gngpp** [comment]
> 一个是4.5的版本，一个是最新的

我调回去吧

**Comment by GuessMine** [comment]
感谢，我试试

**Comment by GuessMine** [comment]
今天的版本，我试了还是一样

**Comment by gngpp** [comment]
> 今天的版本，我试了还是一样

因为时间太短了，没明显感觉，我又调了，等几分钟
