### ISSUE TITLE
[main]主题模式改为 跟随系统 后有BUG

### ISSUE THREAD

**Issue by VIKINGYFY** [gngpp/luci-theme-design#32]
应该是在重构代码后出现的

![QQ图片20230321211508](https://user-images.githubusercontent.com/7755795/226617231-27ba19fe-15e6-4dc0-ab85-f5b3f0ba6201.jpg)

![QQ截图20230321211313](https://user-images.githubusercontent.com/7755795/226617238-189cbe0e-9bc0-4dc0-b217-94c6be5396ab.png)

**Comment by gngpp** [comment]
> 应该是在重构代码后出现的
> 
> ![QQ图片20230321211508](https://user-images.githubusercontent.com/7755795/226617231-27ba19fe-15e6-4dc0-ab85-f5b3f0ba6201.jpg)
> 
> ![QQ截图20230321211313](https://user-images.githubusercontent.com/7755795/226617238-189cbe0e-9bc0-4dc0-b217-94c6be5396ab.png)

已经修复了，等几分钟构建出来

> 应该是在重构代码后出现的
> 
> ![QQ图片20230321211508](https://user-images.githubusercontent.com/7755795/226617231-27ba19fe-15e6-4dc0-ab85-f5b3f0ba6201.jpg)
> 
> ![QQ截图20230321211313](https://user-images.githubusercontent.com/7755795/226617238-189cbe0e-9bc0-4dc0-b217-94c6be5396ab.png)

已修复：https://github.com/gngpp/luci-theme-design/releases/tag/v5.5.6-20230321
