### ISSUE TITLE
[main] 右上角的 定时刷新 开关图标没了

### ISSUE THREAD

**Issue by VIKINGYFY** [gngpp/luci-theme-design#34]
右上角的 定时刷新 开关图标没了，但鼠标移上去能点击，也有作用

**Comment by gngpp** [comment]
图呢？

**Comment by VIKINGYFY** [comment]
> 图呢？

来了来了
![image](https://user-images.githubusercontent.com/7755795/227729395-84f8b69c-0b77-404e-b01c-5f0d512ebf67.png)

**Comment by gngpp** [comment]
> > 图呢？
> 
> 来了来了
> ![image](https://user-images.githubusercontent.com/7755795/227729395-84f8b69c-0b77-404e-b01c-5f0d512ebf67.png)
> 

版本

**Comment by gngpp** [comment]
> > 图呢？
> 
> 来了来了
> ![image](https://user-images.githubusercontent.com/7755795/227729395-84f8b69c-0b77-404e-b01c-5f0d512ebf67.png)
> 

肯定是我没发版你就开始拉下来了

**Comment by gngpp** [comment]
![image](https://user-images.githubusercontent.com/51810656/227749391-4dd91c54-a70f-4d96-9fce-d55181881694.png)
拉版记得带上tag：git clone -b v5.5.9-20230325 https://github.com/gngpp/luci-theme-design.git

**Comment by VIKINGYFY** [comment]
> ![image](https://user-images.githubusercontent.com/51810656/227749391-4dd91c54-a70f-4d96-9fce-d55181881694.png) 拉版记得带上tag：git clone -b v5.5.9-20230325 https://github.com/gngpp/luci-theme-design.git

更新了，升级安装的，还是没有，已清空浏览器缓存，刷新浏览器的时候可以看见图标闪了一下
![image](https://user-images.githubusercontent.com/7755795/227751779-0795874c-288b-43c2-a8b9-6c5fb9ed1bc8.png)

**Comment by gngpp** [comment]
> > ![image](https://user-images.githubusercontent.com/51810656/227749391-4dd91c54-a70f-4d96-9fce-d55181881694.png) 拉版记得带上tag：git clone -b v5.5.9-20230325 https://github.com/gngpp/luci-theme-design.git
> 
> 更新了，升级安装的，还是没有，已清空浏览器缓存，刷新浏览器的时候可以看见图标闪了一下 ![image](https://user-images.githubusercontent.com/7755795/227751779-0795874c-288b-43c2-a8b9-6c5fb9ed1bc8.png)

这我就不知道你了，我没有问题
![image](https://user-images.githubusercontent.com/51810656/227751901-c882ed94-0bc3-45df-ad70-1205a9b7683d.png)

**Comment by gngpp** [comment]
> > ![image](https://user-images.githubusercontent.com/51810656/227749391-4dd91c54-a70f-4d96-9fce-d55181881694.png) 拉版记得带上tag：git clone -b v5.5.9-20230325 https://github.com/gngpp/luci-theme-design.git
> 
> 更新了，升级安装的，还是没有，浏览器是EDGE（111.0.1661.54 正式版本 64 位）已清空浏览器缓存，刷新浏览器的时候可以看见图标闪了一下 ![image](https://user-images.githubusercontent.com/7755795/227751779-0795874c-288b-43c2-a8b9-6c5fb9ed1bc8.png)

会F12，自行debug看一下html吧

**Comment by gngpp** [comment]
> > ![image](https://user-images.githubusercontent.com/51810656/227749391-4dd91c54-a70f-4d96-9fce-d55181881694.png) 拉版记得带上tag：git clone -b v5.5.9-20230325 https://github.com/gngpp/luci-theme-design.git
> 
> 更新了，升级安装的，还是没有，浏览器是EDGE（111.0.1661.54 正式版本 64 位）已清空浏览器缓存，刷新浏览器的时候可以看见图标闪了一下 ![image](https://user-images.githubusercontent.com/7755795/227751779-0795874c-288b-43c2-a8b9-6c5fb9ed1bc8.png)

![image](https://user-images.githubusercontent.com/51810656/227752215-42edb26e-0ec4-463b-a594-62585dab30a6.png)

**Comment by VIKINGYFY** [comment]
> > > ![image](https://user-images.githubusercontent.com/51810656/227749391-4dd91c54-a70f-4d96-9fce-d55181881694.png) 拉版记得带上tag：git clone -b v5.5.9-20230325 https://github.com/gngpp/luci-theme-design.git
> > 
> > 
> > 更新了，升级安装的，还是没有，浏览器是EDGE（111.0.1661.54 正式版本 64 位）已清空浏览器缓存，刷新浏览器的时候可以看见图标闪了一下 ![image](https://user-images.githubusercontent.com/7755795/227751779-0795874c-288b-43c2-a8b9-6c5fb9ed1bc8.png)
> 
> ![image](https://user-images.githubusercontent.com/51810656/227752215-42edb26e-0ec4-463b-a594-62585dab30a6.png)

我换了个浏览器试了一下是有的，就这个EDGE没有，算了，不管了，谢谢大佬

**Comment by gngpp** [comment]
> > > > ![image](https://user-images.githubusercontent.com/51810656/227749391-4dd91c54-a70f-4d96-9fce-d55181881694.png) 拉版记得带上tag：git clone -b v5.5.9-20230325 https://github.com/gngpp/luci-theme-design.git
> > > 
> > > 
> > > 更新了，升级安装的，还是没有，浏览器是EDGE（111.0.1661.54 正式版本 64 位）已清空浏览器缓存，刷新浏览器的时候可以看见图标闪了一下 ![image](https://user-images.githubusercontent.com/7755795/227751779-0795874c-288b-43c2-a8b9-6c5fb9ed1bc8.png)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/51810656/227752215-42edb26e-0ec4-463b-a594-62585dab30a6.png)
> 
> 我换了个浏览器试了一下是有的，就这个EDGE没有，算了，不管了，谢谢大佬

![image](https://user-images.githubusercontent.com/51810656/227752347-f9a2cc22-e444-4ae0-8233-1bd8713e9541.png)

**Comment by VIKINGYFY** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/51810656/227749391-4dd91c54-a70f-4d96-9fce-d55181881694.png) 拉版记得带上tag：git clone -b v5.5.9-20230325 https://github.com/gngpp/luci-theme-design.git
> > > > 
> > > > 
> > > > 更新了，升级安装的，还是没有，浏览器是EDGE（111.0.1661.54 正式版本 64 位）已清空浏览器缓存，刷新浏览器的时候可以看见图标闪了一下 ![image](https://user-images.githubusercontent.com/7755795/227751779-0795874c-288b-43c2-a8b9-6c5fb9ed1bc8.png)
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/51810656/227752215-42edb26e-0ec4-463b-a594-62585dab30a6.png)
> > 
> > 
> > 我换了个浏览器试了一下是有的，就这个EDGE没有，算了，不管了，谢谢大佬
> 
> ![image](https://user-images.githubusercontent.com/51810656/227752347-f9a2cc22-e444-4ae0-8233-1bd8713e9541.png)

找到问题了，我用了替换网页字体的扩展，把这个关了就有，谢谢大佬回复
