### ISSUE TITLE
[main] 手机页面名字过长会出问题

### ISSUE THREAD

**Issue by VIKINGYFY** [gngpp/luci-theme-design#35]
![Screenshot_20230329_085104_com huawei browser](https://user-images.githubusercontent.com/7755795/228399191-fdbb16d9-22d8-4e6c-9e77-36768e3595bc.jpg)
![Screenshot_20230329_085059_com huawei browser](https://user-images.githubusercontent.com/7755795/228399373-2909a6b4-42a2-454c-86b6-9e01624135cc.jpg)

**Comment by gngpp** [comment]
那你缩短一点不就行了，谁叫你搞这么长，元素没地方放了

**Comment by gngpp** [comment]
还有不要搞乱七八糟特殊字符，字体不支持，不支持就会换行错位显示

**Comment by gngpp** [comment]
> 还有不要搞乱七八糟特殊字符，字体不支持，不支持就会换行错位显示

想支持就自己加字符，为了极限压缩文件体积只能这么做
