### ISSUE TITLE
反馈个bug

### ISSUE THREAD

**Issue by zxc173123** [gngpp/luci-theme-design#36]
design主题在360极速浏览器会无限刷新导致进不了后台，要切换到兼容模式才能进后台不过会显示不全，再切换回极速模式就好了。

**Comment by gngpp** [comment]
> 360极速浏览器进后台会无限刷新开兼容模式才能进后台

分支+版本？

**Comment by zxc173123** [comment]
<img width="1182" alt="9563952b380e3668b90726ba00aa1712_181931p3mspms130s99ps0" src="https://user-images.githubusercontent.com/56154254/229349713-a2279ddc-1601-4eb4-bff7-a929df1588bf.png">
https://www.right.com.cn/FORUM/thread-8263340-1-1.html

**Comment by gngpp** [comment]
> https://www.right.com.cn/FORUM/thread-8263340-1-1.html

我劝你用谷歌浏览器再试试，据我所知360浏览器一堆问题，很难适配

**Comment by zxc173123** [comment]
降级浏览器版本就没问题了，看来是360的问题
