### ISSUE TITLE
[main] 易有云系列图标没有适配

### ISSUE THREAD

**Issue by VIKINGYFY** [gngpp/luci-theme-design#37]
项目地址
https://github.com/linkease/nas-packages
https://github.com/linkease/nas-packages-luci
包名
luci-app-istorex（首页）
luci-app-quickstart（网络向导）
![QQ图片20230401201452](https://user-images.githubusercontent.com/7755795/229287991-644c5f5f-f6c1-47f5-90ea-88f4ef0f75f4.png)

**Comment by gngpp** [comment]
按F12，看看data-title

**Comment by gngpp** [comment]
> 按F12，看看data-title

<img width="1467" alt="image" src="https://user-images.githubusercontent.com/51810656/229288475-f5a1bbbf-18da-4c31-8a64-586fd52822cc.png">

**Comment by VIKINGYFY** [comment]
> > 按F12，看看data-title
> 
> <img alt="image" width="1467" src="https://user-images.githubusercontent.com/51810656/229288475-f5a1bbbf-18da-4c31-8a64-586fd52822cc.png">

额，那等明天吧，现在没有刷固件，正在编译中

**Comment by VIKINGYFY** [comment]
> 按F12，看看data-title

首页
QuickStart
网络向导
NetworkGuide

**Comment by gngpp** [comment]
> > 按F12，看看data-title
> 
> 首页 QuickStart 网络向导 NetworkGuide
> 
> istore那少了个箭头？

没有少，二级菜单才有箭头

**Comment by gngpp** [comment]
https://github.com/gngpp/luci-theme-design/releases/tag/v5.6.0-20230402
