### ISSUE TITLE
[main] 新版这个滑动条，能否增加点高度，现在对小屏用户很不友好

### ISSUE THREAD

**Issue by VIKINGYFY** [gngpp/luci-theme-design#78]
我现在在笔记本上看的，15.6寸，1080P分辨率，浏览器缩放110%，很不好点，可否在增加点高度？

![image](https://user-images.githubusercontent.com/7755795/230599639-7014a46a-cd20-4a37-801b-114728ad7342.png)

**Comment by gngpp** [comment]
https://github.com/gngpp/luci-theme-design/releases/tag/v5.7.3-20230417
